import os
import json
import docker
import dotenv
from state import State, Generation
from langchain_nvidia_ai_endpoints import ChatNVIDIA
from tools import make_folder, make_file, setting_environment, run_code

dotenv.load_dotenv()

model = ChatNVIDIA(
    model="deepseek-ai/deepseek-v4-pro",
    api_key=os.getenv("NVIDIA_API_KEY"),
    temperature=0.3,
    timeout=120,
    max_tokens=4096
)

# Use structured output so the model just returns all files at once
structured_model = model.with_structured_output(Generation)

async def Generation_Agent(state: State):
    print("\n🚀 --- GENERATION AGENT STARTED --- 🚀")
    
    system_prompt = """
    You are the Code Generation Agent in an AI software compiler. 
    Your job is to read the validated architectures (API, DB, UI, Design) and build the project.
    
    Generate the complete project based on the schemas provided:
    - Backend: Node.js Express server (API) + basic SQLite database connection (DB).
    - Frontend: A basic HTML/JS/CSS frontend (UI).
    - Config: package.json with necessary dependencies (express, sqlite3, cors, etc).
    
    CRITICAL: YOU ARE RESTRICTED BY MAX_TOKENS. 
    Keep the generated code AS SHORT AND MINIMAL AS POSSIBLE. Do not generate all endpoints, just 1 or 2 mock endpoints to prove it works. Do not generate full CSS. Keep it under 200 lines total across all files.
    
    IMPORTANT FILE PATH RULE:
    Write all files directly to the root directory (e.g. just 'package.json', not 'backend/package.json'). Do not use subdirectories.
    
    Output a JSON object with a list of all files.
    """
    
    state_context = {
        "api": state.get("api").model_dump() if state.get("api") else {},
        "db": state.get("db").model_dump() if state.get("db") else {},
        "ui": state.get("ui").model_dump() if state.get("ui") else {},
    }
    
    prompt = f"Here is the complete validated architecture:\n{state_context}\n\nBuild the complete project (API backend, DB schema logic, and UI components)."
    
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": prompt}
    ]
    
    print("Generating code (this may take a minute)...")
    
    # Get the files from the AI
    response = await structured_model.ainvoke(messages)
    
    if not response or not response.files:
        print("❌ ERROR: No files were generated by the AI.")
        return {"generation": Generation(files=[])}
        
    print(f"✅ AI generated {len(response.files)} files. Writing them using tools...")
    
    # 1. Scaffold ALL code files using make_file tool
    for file in response.files:
        make_file.invoke({"file_name": file.filepath, "content": file.content})
        print(f"   -> Wrote {file.filepath}")
        
    # 2. Call setting_environment() to install dependencies
    print("📦 Installing dependencies...")
    env_result = setting_environment.invoke({})
    print(env_result)
    
    # 3. Call run_code() to test the project
    print("🧪 Testing syntax...")
    test_result = run_code.invoke({"command": "node --check server.js"})
    print(test_result)
    
    print("--------------------------------------\n")
    
    # Return the Generation object for state
    return {"generation": response}
